-- Sales DW relational model (generated by model.py)
-- Load order respects FK dependencies (dims first, fact last).

CREATE TABLE dim_date (
    date_key               BIGINT NOT NULL,
    full_date              DATE,
    day                    BIGINT,
    month                  BIGINT,
    month_name             VARCHAR(20),
    quarter                BIGINT,
    year                   BIGINT,
    PRIMARY KEY (date_key)
);

CREATE TABLE dim_product (
    product_key            BIGINT NOT NULL,
    product_id             BIGINT,
    product_name           VARCHAR(255),
    product_number         VARCHAR(50),
    color                  VARCHAR(50),
    size                   VARCHAR(50),
    category               VARCHAR(100),
    subcategory            VARCHAR(100),
    standard_cost          NUMERIC(18,4),
    list_price             NUMERIC(18,4),
    PRIMARY KEY (product_key)
);

CREATE TABLE dim_customer (
    customer_key           BIGINT NOT NULL,
    customer_id            BIGINT,
    customer_type          VARCHAR(20),
    territory_id           BIGINT,
    PRIMARY KEY (customer_key)
);

CREATE TABLE dim_channel (
    channel_key            BIGINT NOT NULL,
    channel_name           VARCHAR(20),
    PRIMARY KEY (channel_key)
);

CREATE TABLE dim_aspect (
    aspect_key             BIGINT NOT NULL,
    aspect_name            VARCHAR(50),
    PRIMARY KEY (aspect_key)
);

CREATE TABLE dim_sentiment (
    sentiment_key          BIGINT NOT NULL,
    sentiment_label        VARCHAR(20),
    sentiment_score        BIGINT,
    PRIMARY KEY (sentiment_key)
);

CREATE TABLE fact_sales (
    sales_key              BIGINT NOT NULL,
    date_key               BIGINT NOT NULL,
    customer_key           BIGINT NOT NULL,
    product_key            BIGINT NOT NULL,
    channel_key            BIGINT NOT NULL,
    sales_order_id         BIGINT,
    source_type            VARCHAR(20),
    order_qty              BIGINT,
    unit_price             NUMERIC(18,4),
    unit_price_discount    NUMERIC(18,4),
    line_total             NUMERIC(18,4),
    sales_count            BIGINT,
    PRIMARY KEY (sales_key),
    FOREIGN KEY (date_key) REFERENCES dim_date (date_key),
    FOREIGN KEY (customer_key) REFERENCES dim_customer (customer_key),
    FOREIGN KEY (product_key) REFERENCES dim_product (product_key),
    FOREIGN KEY (channel_key) REFERENCES dim_channel (channel_key)
);

CREATE TABLE fact_sentiment (
    sentiment_fact_key     BIGINT NOT NULL,
    date_key               BIGINT NOT NULL,
    product_key            BIGINT NOT NULL,
    aspect_key             BIGINT NOT NULL,
    sentiment_key          BIGINT NOT NULL,
    tweet_id               VARCHAR(32),
    screen_name            VARCHAR(100),
    lang                   VARCHAR(10),
    source                 VARCHAR(50),
    verified               BOOLEAN,
    is_spike               BOOLEAN,
    followers_count        BIGINT,
    favorite_count         BIGINT,
    retweet_count          BIGINT,
    engagement_total       BIGINT,
    sentiment_score        BIGINT,
    tweet_count            BIGINT,
    PRIMARY KEY (sentiment_fact_key),
    FOREIGN KEY (date_key) REFERENCES dim_date (date_key),
    FOREIGN KEY (product_key) REFERENCES dim_product (product_key),
    FOREIGN KEY (aspect_key) REFERENCES dim_aspect (aspect_key),
    FOREIGN KEY (sentiment_key) REFERENCES dim_sentiment (sentiment_key)
);
